### PR TITLE
Clean up whitespace #24

### PR DESCRIPTION
**Pull request by JensLorenz**
This PR will modify slightly the code style configuration file and
provides later an cleaned version of AudioManager.
The update will be done once all previous PR are successfully merged.

### CODE REVIEW

**Comment by gunnarx** [comment]
@JensLorenz Any idea why there are so many lines that moved in the config file?  Did eclipse change the order of lines?  Because it's hard to see the actual diff...  One idea I had is to sort all the lines in one commit (without changing), then doing the change in another commit, so the diff can then be reviewed.  Just a thought.

**Comment by gunnarx** [comment]
I did the above proposal in #31 if it helps

**Comment by gunnarx** [comment]
By the way, not sure if the repo policy is to rebase PRs during merge but if it isn't please note that e2bc709 is weeks behind current master @JensLorenz.  (You might prefer to rebase it to avoid a merge commit)

**Comment by JensLorenz** [comment]
@gunnarx: Thanx for the cleanup. I would like to merge yours and after I rebase this PR - or open a new one.

**Comment by JensLorenz** [comment]
Close this PR. Proposal #31 is merged. New one will be created with the cleanup.

**Pull request closed without merging**
