### PR TITLE
typo correction on CAmSerializer.h

### PR DESCRIPTION
**Pull request by daduki**
CAmDelegagePtr > CAmDelegatePtr
mListDelegatePoiters > mListDelegatePointers
getListDelegatePoiters > getListDelegatePointers

### CODE REVIEW

**Comment by mkoch-aditg** [comment]
Hello daduki,
thank you for contributing. Regarding CAmDelegagePtr and mListDelegatePoiters, they are declared private and can be corrected without any impact on existing applications.
Regarding function getListDelegatePoiters(), it is part of the public interface and might be used by example plugins, customer-designed plugins and also customer client applications. So correcting this small typo should be done with great care. I propose establishing a new function with the correct spelling beside the existing, redirect the existing and make a note to it which marks it as deprecated.

We can discuss this in the associated mailing list. Please subscribe to https://lists.genivi.org/mailman/listinfo/genivi-audio-manager_lists.genivi.org.

**Comment by daduki** [comment]
As you suggested, getListDelegatePointersSize would be good for renaming.
Also inline redirection is added (getListDelegagePoiters to getListDelegatePointersSize) on #53 

Update CAmSerializer.h(typo correction regarding getListDelegagePoiters) #53

**Comment by daduki** [comment]
In #53 all the changes are included
If #53 is merged, please ignore this commit(#51)
Thanks

**Comment by daduki** [comment]
Using #53 instead of #51 
So, I closed this.

**Pull request closed without merging**
